#!/bin/bash

DEB="${@:1}"
[[ -z $DEB ]] && { echo "freightadder: debian package name is required"; exit 1; }

CONFIG=/get.nitrous.io/.freight.conf
DIST="nitrous"

[[ ! -f $CONFIG ]] && { echo "freightadder: Config file not found"; exit 1; }

freight add -c $CONFIG $DEB apt/$DIST
